---
- hosts: all
  become: true
  become_user: matstar

  roles:
    - role_docker_compose  # Utilisation du rôle téléchargé

  vars_files:
    - vars/main.yml
  tasks:
    - name: Déployer le fichier Docker Compose
      include_tasks: tasks/docker-compose.yml

    - name: Effectuer la communication via webhook
      include_tasks: tasks/webhook.yml