---
- hosts: all
  become: true
  become_user: matstar
  tasks: 
    - name: Loads vars
      include_vars: vars/main.yml
    - name: Installation and configuration of crontab
      include_tasks: tasks/docker.yml
    - name: Solution deployement
      include_tasks: tasks/docker-compose.yml