---
# tasks/docker.yml
- name: Vérifier si Docker est installé
  command: which docker
  register: docker_installed
  changed_when: false

- name: Installer Docker si nécessaire
  apt:
    name: docker.io
    state: present
  when: docker_installed.rc != 0

- name: Vérifier si Docker est en cours d'exécution
  command: systemctl is-active docker
  register: docker_status
  changed_when: false

- name: Démarrer Docker si nécessaire
  service:
    name: docker
    state: started
  when: docker_status.stdout != "active"

- name: Vérifier si l'image Dashy est déjà présente
  command: docker images -q {{ image_name }}
  register: docker_image_exists
  changed_when: false

- name: Télécharger l'image Docker uniquement si elle est absente
  community.docker.docker_image:
    name: "{{ image_name }}"
    source: pull
    state: present
  when: docker_image_exists.stdout == ""