---
# tasks/docker.yml
- name: Ajouter /usr/local/bin au PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:/usr/local/bin'
    create: yes

- name: Recharger l'environnement shell
  shell: source ~/.bashrc

- name: Vérifier si Docker est installé
  command: which docker
  register: docker_installed
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Installer Docker si nécessaire
  apt:
    name: docker.io
    state: present
  when: docker_installed.rc != 0

- name: Vérifier si Docker tourne
  command: systemctl is-active pkg-ContainerManager-dockerd
  register: docker_status
  changed_when: false
  failed_when: docker_status.rc != 0 and docker_status.stdout != "inactive"

- name: Démarrer Docker si nécessaire
  command: systemctl start pkg-ContainerManager-dockerd
  when: docker_status.stdout != "active"

- name: Vérifier si l'image Docker Dashy est déjà présente
  command: /usr/local/bin/docker images -q lissy93/dashy:latest
  register: docker_image_exists
  changed_when: false
  failed_when: docker_image_exists is undefined

- name: Télécharger l'image Docker uniquement si elle est absente
  command: /usr/local/bin/docker pull lissy93/dashy:latest
  when: docker_image_exists.stdout | length == 0