---
- name: Copier le fichier Docker Compose
  template:
    src: "files/docker-compose.j2"
    dest: "{{ compose_file }}"
    mode: 0644

- name: Copier le fichier de configuration Dashy
  template:
    src: "files/dashyconf.j2"
    dest: "{{ config_file }}"
    mode: 0644

- name: Lancer Docker Compose
  command: /usr/local/bin/docker-compose -f {{ compose_file }} up -d
  args:
    chdir: "{{ docker_path }}"