---
# tasks/docker.yml
- name: Ajouter {{ docker_bin }} au PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=${{ docker_bin }}'
    create: yes

- name: Recharger l'environnement shell
  shell: source ~/.bashrc


- name: Installer Docker si nécessaire
  apt:
    name: docker.io
    state: present
  when: not docker_installed.stat.exists


- name: Vérifier si Docker est installé
  stat:
    path: {{ docker_bin }}
  register: docker_installed
  changed_when: false

- name: Installer Docker si nécessaire
  apt:
    name: docker.io
    state: present
  when: not docker_installed.stat.exists

- name: Vérifier si Docker est en cours d'exécution
  command: systemctl is-active docker
  register: docker_status
  changed_when: false
  when: docker_installed.stat.exists

- name: Démarrer Docker si nécessaire
  service:
    name: docker
    state: started
  when: docker_status.stdout != "active" and docker_installed.stat.exists

- name: Vérifier si l'image Dashy est déjà présente
  command: docker images -q {{ image_name }}
  register: docker_image_exists
  changed_when: false
  when: docker_installed.stat.exists

- name: Télécharger l'image Docker uniquement si elle est absente
  community.docker.docker_image:
    name: "{{ image_name }}"
    source: pull
    state: present
  when: docker_image_exists.stdout == "" and docker_installed.stat.exists