---
# tasks file for {{ container_name }} 
- name: Check if {{ container_name }} is running
  command: /usr/local/bin/docker inspect -f "{{ '{{ .State.Status }}' }}" {{ container_name }}
  register: docker_status
  failed_when: docker_status.rc != 0
  changed_when: false

- name: Print Docker running status
  debug:
    msg: "Docker is running: {{ docker_status.stdout }}"
  when: "'running' in docker_status.stdout"

- name: Docker is not running
  debug:
    msg: "Docker is not running or not installed"
  when: "'running' not in docker_status.stdout"

- name: Docker is not running, attempting to start it
  debug:
    msg: "Docker is not running or not installed, attempting to start it"
  when: "'running' not in docker_status.stdout"

- name: Download Docker image {{ image_name }}
  command: /var/packages/ContainerManager/target/usr/bin/docker pull {{ image_name }}
  register: docker_pull
  ignore_errors: yes

- name: Print Docker image pull status {{ image_name }}
  debug:
    msg: "Docker image pull result: {{ docker_pull.stdout }}"
  when: docker_pull.rc == 0

- name: Failed to pull Docker image {{ image_name }}
  debug:
    msg: "Failed to pull Docker image"
  when: docker_pull.rc != 0