---
# tasks file for zabbix
- name: Check if Docker service is running
  command: systemctl status pkgctl-Docker
  register: docker_status
  ignore_errors: yes

- name: Print Docker running status
  debug:
    msg: "Docker is running: {{ docker_status.stdout }}"
  when: "'enable' in docker_status.stdout and 'active' in docker_status.stdout"

- name: Docker is not running
  debug:
    msg: "Docker is not running or not installed"
  when: "'enable' not in docker_status.stdout or 'active' not in docker_status.stdout"

- name: Docker is not running, attempting to start it
  debug:
    msg: "Docker is not running or not installed, attempting to start it"
  when: "'enable' not in docker_status.stdout or 'active' not in docker_status.stdout"

- name: Download Docker image lissy93/dashy:latest
  command: /var/packages/ContainerManager/target/usr/bin/docker pull lissy93/dashy:latest
  register: docker_pull
  ignore_errors: yes

- name: Print Docker image pull status lissy93/dashy:latest
  debug:
    msg: "Docker image pull result: {{ docker_pull.stdout }}"
  when: docker_pull.rc == 0

- name: Failed to pull Docker image lissy93/dashy:latest
  debug:
    msg: "Failed to pull Docker image"
  when: docker_pull.rc != 0